"""sync_models

Revision ID: 461df314e3b8
Revises: 0002
Create Date: 2026-03-10 15:50:20.288944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461df314e3b8'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lecturers', 'office_hours',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False,
               postgresql_using="CASE WHEN office_hours ~ '^\\d{4}-\\d{2}-\\d{2}' THEN office_hours::timestamp ELSE '2024-01-01 00:00:00'::timestamp END")
    op.drop_column('lecturers', 'title')
    op.drop_column('rooms', 'is_available')
    op.drop_column('rooms', 'room_type')
    op.drop_column('student_tests', 'is_registered')
    op.drop_constraint(op.f('tests_lecturer_id_fkey'), 'tests', type_='foreignkey')
    op.drop_column('tests', 'lecturer_id')
    op.alter_column('users', 'hashed_password', new_column_name='password')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    op.add_column('tests', sa.Column('lecturer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tests_lecturer_id_fkey'), 'tests', 'lecturers', ['lecturer_id'], ['id'])
    op.add_column('student_tests', sa.Column('is_registered', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('room_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('lecturers', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('lecturers', 'office_hours',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
