"""lecturer to division many to many

Revision ID: c5be2dec5833
Revises: 461df314e3b8
Create Date: 2026-03-10 16:27:45.787933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5be2dec5833'
down_revision: Union[str, Sequence[str], None] = '461df314e3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer_divisions',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], ),
    sa.PrimaryKeyConstraint('lecturer_id', 'division_id')
    )
    op.alter_column('campuses', 'address_details',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('lecturers_division_id_fkey'), 'lecturers', type_='foreignkey')
    op.drop_column('lecturers', 'division_id')
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rooms', 'available_from',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('rooms', 'available_until',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('students', 'division_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'enrollment_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tests', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'enrollment_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'division_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'available_until',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('rooms', 'available_from',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('lecturers', sa.Column('division_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('lecturers_division_id_fkey'), 'lecturers', 'divisions', ['division_id'], ['id'])
    op.alter_column('campuses', 'address_details',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('lecturer_divisions')
    # ### end Alembic commands ###
