from .user import User
from .session import Session
from .campus import Campus
from .division import Division
from .campus_building import CampusBuilding
from .room import Room
from .student import Student
from .lecturer import Lecturer
from .test import Test
from .student_test import StudentTest
